
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Tanya
 */
public class viewcv extends javax.swing.JFrame {

    /**
     * Creates new form viewcv
     */
    public viewcv() {
        initComponents();
    }
    String loginid;
    public void gencode(String a)
    { loginid=a;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane4 = new javax.swing.JScrollPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        Secentha1 = new javax.swing.JPanel();
        second1 = new javax.swing.JLabel();
        Thirda1 = new javax.swing.JLabel();
        Thirdb1 = new javax.swing.JTextField();
        Fourtha1 = new javax.swing.JLabel();
        Fourthb1 = new javax.swing.JTextField();
        fiftha1 = new javax.swing.JLabel();
        fifthb1 = new javax.swing.JTextField();
        Sixtha1 = new javax.swing.JLabel();
        Seventha1 = new javax.swing.JLabel();
        Seventb1 = new javax.swing.JTextField();
        Eighta1 = new javax.swing.JLabel();
        Eightb1 = new javax.swing.JTextField();
        Ninea1 = new javax.swing.JLabel();
        Nineb1 = new javax.swing.JTextField();
        Tena1 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        Tenb1 = new javax.swing.JTextArea();
        Elevena1 = new javax.swing.JLabel();
        Elevenb1 = new javax.swing.JTextField();
        Twelvea1 = new javax.swing.JLabel();
        Twelveb1 = new javax.swing.JTextField();
        Thirteena1 = new javax.swing.JLabel();
        Thirteenb1 = new javax.swing.JTextField();
        Fourteena1 = new javax.swing.JLabel();
        Fourteenb1 = new javax.swing.JTextField();
        Fifteena1 = new javax.swing.JLabel();
        Fifteenb1 = new javax.swing.JTextField();
        Fourteend1 = new javax.swing.JTextField();
        Fourteenc1 = new javax.swing.JLabel();
        Fifteenc1 = new javax.swing.JLabel();
        Fifteend1 = new javax.swing.JTextField();
        Sixteena1 = new javax.swing.JLabel();
        Sixteenb1 = new javax.swing.JTextField();
        Sixteenc1 = new javax.swing.JLabel();
        Sixteend1 = new javax.swing.JTextField();
        Seventeena1 = new javax.swing.JLabel();
        Seventeenc1 = new javax.swing.JLabel();
        Seventeenb1 = new javax.swing.JTextField();
        Seventeend1 = new javax.swing.JTextField();
        Twentyb2 = new javax.swing.JTextField();
        Eighteenb2 = new javax.swing.JTextField();
        jScrollPane9 = new javax.swing.JScrollPane();
        Twentytwob3 = new javax.swing.JTextArea();
        Eighteenc2 = new javax.swing.JLabel();
        Twentyonea3 = new javax.swing.JLabel();
        Nineteenc2 = new javax.swing.JLabel();
        Nineteenb2 = new javax.swing.JTextField();
        Twentytwoa3 = new javax.swing.JLabel();
        Eighteend2 = new javax.swing.JTextField();
        Nineteend2 = new javax.swing.JTextField();
        Twentya2 = new javax.swing.JLabel();
        Twentyoneb3 = new javax.swing.JTextField();
        Nineteena2 = new javax.swing.JLabel();
        Eighteena2 = new javax.swing.JLabel();
        Thirda2 = new javax.swing.JLabel();
        Thirdb2 = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        Sixtha2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images (1).jpeg"))); // NOI18N

        Secentha1.setForeground(new java.awt.Color(0, 0, 204));

        second1.setFont(new java.awt.Font("Trebuchet MS", 1, 16)); // NOI18N
        second1.setText("The CV details are as follows:");

        Thirda1.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        Thirda1.setForeground(new java.awt.Color(0, 0, 204));
        Thirda1.setText(" Student's Name");

        Thirdb1.setText(" ");
        Thirdb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Thirdb1ActionPerformed(evt);
            }
        });

        Fourtha1.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        Fourtha1.setForeground(new java.awt.Color(0, 0, 204));
        Fourtha1.setText(" Father's Name");

        Fourthb1.setText(" ");

        fiftha1.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        fiftha1.setForeground(new java.awt.Color(0, 0, 204));
        fiftha1.setText(" Mother's Name");

        fifthb1.setText(" ");

        Sixtha1.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        Sixtha1.setForeground(new java.awt.Color(0, 0, 204));
        Sixtha1.setText(" Gender");

        Seventha1.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        Seventha1.setForeground(new java.awt.Color(0, 0, 204));
        Seventha1.setText(" DOB");

        Seventb1.setText("dd/mm/yyyy");
        Seventb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Seventb1ActionPerformed(evt);
            }
        });

        Eighta1.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        Eighta1.setForeground(new java.awt.Color(0, 0, 204));
        Eighta1.setText(" E-mail ID");

        Eightb1.setText("  ");

        Ninea1.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        Ninea1.setForeground(new java.awt.Color(0, 0, 204));
        Ninea1.setText(" Mobile Number");

        Nineb1.setText(" ");
        Nineb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Nineb1ActionPerformed(evt);
            }
        });

        Tena1.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        Tena1.setForeground(new java.awt.Color(0, 0, 204));
        Tena1.setText(" Address");

        Tenb1.setColumns(20);
        Tenb1.setRows(5);
        jScrollPane3.setViewportView(Tenb1);

        Elevena1.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        Elevena1.setForeground(new java.awt.Color(0, 0, 204));
        Elevena1.setText("  Branch");

        Elevenb1.setText(" ");

        Twelvea1.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        Twelvea1.setForeground(new java.awt.Color(0, 0, 204));
        Twelvea1.setText(" College");

        Twelveb1.setText(" ");

        Thirteena1.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        Thirteena1.setForeground(new java.awt.Color(0, 0, 204));
        Thirteena1.setText(" Semester");

        Thirteenb1.setText(" ");

        Fourteena1.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        Fourteena1.setForeground(new java.awt.Color(0, 0, 204));
        Fourteena1.setText(" 10th ( %)");

        Fourteenb1.setText(" ");

        Fifteena1.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        Fifteena1.setForeground(new java.awt.Color(0, 0, 204));
        Fifteena1.setText(" 12th(%)");

        Fifteenb1.setText("  ");

        Fourteend1.setText(" ");

        Fourteenc1.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        Fourteenc1.setForeground(new java.awt.Color(0, 0, 204));
        Fourteenc1.setText(" Passing Year");

        Fifteenc1.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        Fifteenc1.setForeground(new java.awt.Color(0, 0, 204));
        Fifteenc1.setText(" Passing Year");

        Fifteend1.setText("      ");

        Sixteena1.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        Sixteena1.setForeground(new java.awt.Color(0, 0, 204));
        Sixteena1.setText(" 1st Year(%)");

        Sixteenb1.setText(" ");

        Sixteenc1.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        Sixteenc1.setForeground(new java.awt.Color(0, 0, 204));
        Sixteenc1.setText(" Passing Year");

        Sixteend1.setText("    ");

        Seventeena1.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        Seventeena1.setForeground(new java.awt.Color(0, 0, 204));
        Seventeena1.setText(" 2nd Year(%)");

        Seventeenc1.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        Seventeenc1.setForeground(new java.awt.Color(0, 0, 204));
        Seventeenc1.setText(" Passing Year");

        Seventeenb1.setText(" ");

        Seventeend1.setText("                ");

        Twentyb2.setText(" ");

        Eighteenb2.setText(" ");
        Eighteenb2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Eighteenb2ActionPerformed(evt);
            }
        });

        Twentytwob3.setColumns(20);
        Twentytwob3.setRows(5);
        jScrollPane9.setViewportView(Twentytwob3);

        Eighteenc2.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        Eighteenc2.setForeground(new java.awt.Color(0, 0, 204));
        Eighteenc2.setText(" Passing Year");

        Twentyonea3.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        Twentyonea3.setForeground(new java.awt.Color(0, 0, 204));
        Twentyonea3.setText("Languages");

        Nineteenc2.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        Nineteenc2.setForeground(new java.awt.Color(0, 0, 204));
        Nineteenc2.setText(" Passing Year");

        Nineteenb2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Nineteenb2ActionPerformed(evt);
            }
        });

        Twentytwoa3.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        Twentytwoa3.setForeground(new java.awt.Color(0, 0, 204));
        Twentytwoa3.setText("Objective");

        Eighteend2.setText("                ");
        Eighteend2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Eighteend2ActionPerformed(evt);
            }
        });

        Nineteend2.setText(" ");
        Nineteend2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Nineteend2ActionPerformed(evt);
            }
        });

        Twentya2.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        Twentya2.setForeground(new java.awt.Color(0, 0, 204));
        Twentya2.setText("Nationality");

        Twentyoneb3.setText(" ");
        Twentyoneb3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Twentyoneb3ActionPerformed(evt);
            }
        });

        Nineteena2.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        Nineteena2.setForeground(new java.awt.Color(0, 0, 204));
        Nineteena2.setText("4th Year(%)");

        Eighteena2.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        Eighteena2.setForeground(new java.awt.Color(0, 0, 204));
        Eighteena2.setText("3rd Year(%)");

        Thirda2.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        Thirda2.setForeground(new java.awt.Color(0, 0, 204));
        Thirda2.setText("Login ID");

        Thirdb2.setText(" ");
        Thirdb2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Thirdb2ActionPerformed(evt);
            }
        });

        jTextField1.setText(" ");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        Sixtha2.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        Sixtha2.setForeground(new java.awt.Color(0, 0, 204));
        Sixtha2.setText("Aggregate");

        jTextField2.setText(" ");
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jButton5.setForeground(new java.awt.Color(204, 0, 204));
        jButton5.setText("Return");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton1.setText("View CV");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Secentha1Layout = new javax.swing.GroupLayout(Secentha1);
        Secentha1.setLayout(Secentha1Layout);
        Secentha1Layout.setHorizontalGroup(
            Secentha1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Secentha1Layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(second1, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(Secentha1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(Secentha1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Secentha1Layout.createSequentialGroup()
                        .addGroup(Secentha1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Elevena1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(Secentha1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(Fifteena1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Fourteena1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Thirteena1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)
                                .addComponent(Twelvea1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addGroup(Secentha1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(Fifteenb1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
                            .addComponent(Fourteenb1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Sixteenb1)
                            .addComponent(Seventeenb1))
                        .addGap(30, 30, 30)
                        .addGroup(Secentha1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Fourteenc1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Sixteenc1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(Secentha1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(Seventeenc1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Fifteenc1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(10, 10, 10)
                        .addGroup(Secentha1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Fourteend1)
                            .addComponent(Fifteend1, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(Secentha1Layout.createSequentialGroup()
                        .addGroup(Secentha1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(Secentha1Layout.createSequentialGroup()
                                .addComponent(Thirda2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Thirdb2, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(105, 105, 105)
                                .addComponent(jButton5))
                            .addGroup(Secentha1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(Secentha1Layout.createSequentialGroup()
                                    .addGroup(Secentha1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(Twentytwoa3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(Twentyonea3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(Twentya2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(Eighteena2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(Nineteena2))
                                    .addGap(29, 29, 29)
                                    .addGroup(Secentha1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(Secentha1Layout.createSequentialGroup()
                                            .addGroup(Secentha1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(Eighteenb2)
                                                .addComponent(Nineteenb2, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGap(29, 29, 29)
                                            .addGroup(Secentha1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(Nineteenc2, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(Eighteenc2))
                                            .addGap(35, 35, 35)
                                            .addGroup(Secentha1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(Eighteend2, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(Nineteend2, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(Secentha1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, Secentha1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(Twentyoneb3, javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(Twentyb2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addGroup(Secentha1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(Elevenb1, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, Secentha1Layout.createSequentialGroup()
                                        .addGroup(Secentha1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(Seventha1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Tena1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Ninea1)
                                            .addComponent(Eighta1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(Secentha1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(Seventb1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Eightb1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Nineb1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(Twelveb1, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Thirteenb1, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(Secentha1Layout.createSequentialGroup()
                                    .addGroup(Secentha1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(Secentha1Layout.createSequentialGroup()
                                            .addComponent(Thirda1)
                                            .addGap(3, 3, 3)
                                            .addComponent(Thirdb1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, Secentha1Layout.createSequentialGroup()
                                            .addGroup(Secentha1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(Secentha1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                    .addComponent(fiftha1, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                                                    .addComponent(Fourtha1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addComponent(Sixtha1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(Sixtha2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(Secentha1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(Fourthb1)
                                                .addComponent(fifthb1)
                                                .addGroup(Secentha1Layout.createSequentialGroup()
                                                    .addGroup(Secentha1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGap(0, 0, Short.MAX_VALUE)))))
                                    .addGap(106, 106, 106)
                                    .addComponent(jButton1))
                                .addGroup(Secentha1Layout.createSequentialGroup()
                                    .addGroup(Secentha1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(Seventeena1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(Sixteena1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGap(213, 213, 213)
                                    .addGroup(Secentha1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(Sixteend1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(Seventeend1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 474, Short.MAX_VALUE))))
        );
        Secentha1Layout.setVerticalGroup(
            Secentha1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Secentha1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(second1)
                .addGap(39, 39, 39)
                .addGroup(Secentha1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Thirda1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Thirdb1)
                    .addComponent(jButton1))
                .addGap(17, 17, 17)
                .addGroup(Secentha1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Thirda2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Thirdb2)
                    .addComponent(jButton5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Secentha1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Fourtha1)
                    .addComponent(Fourthb1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Secentha1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fiftha1)
                    .addComponent(fifthb1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(Secentha1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Sixtha1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(Secentha1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Sixtha2)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(Secentha1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Seventha1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Seventb1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Secentha1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Eighta1)
                    .addComponent(Eightb1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(Secentha1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Ninea1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Nineb1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Secentha1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Tena1)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(Secentha1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Elevena1)
                    .addComponent(Elevenb1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Secentha1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Twelvea1)
                    .addComponent(Twelveb1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Secentha1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Thirteena1)
                    .addComponent(Thirteenb1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(Secentha1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Fourteena1)
                    .addGroup(Secentha1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Fourteenb1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Fourteend1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Fourteenc1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Secentha1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Fifteend1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(Secentha1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Fifteena1)
                        .addComponent(Fifteenb1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Fifteenc1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Secentha1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Sixteena1)
                    .addComponent(Sixteenb1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Sixteenc1)
                    .addComponent(Sixteend1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Secentha1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Seventeena1)
                    .addComponent(Seventeenc1)
                    .addComponent(Seventeenb1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Seventeend1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Secentha1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Eighteena2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Eighteenb2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Eighteenc2)
                    .addComponent(Eighteend2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(Secentha1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Nineteena2)
                    .addComponent(Nineteenb2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Nineteenc2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Nineteend2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(Secentha1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Twentya2)
                    .addComponent(Twentyb2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(Secentha1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Twentyonea3)
                    .addComponent(Twentyoneb3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(Secentha1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Twentytwoa3)
                    .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(645, 645, 645))
        );

        jScrollPane5.setViewportView(Secentha1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(90, 90, 90)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 532, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(1582, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(jLabel28))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 1381, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(471, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel2);

        jScrollPane2.setViewportView(jScrollPane1);

        jScrollPane4.setViewportView(jScrollPane2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 2541, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Twentyoneb3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Twentyoneb3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Twentyoneb3ActionPerformed

    private void Eighteenb2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Eighteenb2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Eighteenb2ActionPerformed

    private void Nineteend2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Nineteend2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Nineteend2ActionPerformed

    private void Nineteenb2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Nineteenb2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Nineteenb2ActionPerformed

    private void Eighteend2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Eighteend2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Eighteend2ActionPerformed

    private void Thirdb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Thirdb1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Thirdb1ActionPerformed

    private void Seventb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Seventb1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Seventb1ActionPerformed

    private void Nineb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Nineb1ActionPerformed
       
        // TODO add your handling code here:
    }//GEN-LAST:event_Nineb1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
       Recruiterhome rh=new Recruiterhome();
       rh.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    try
    {Thirdb2.setText(loginid);
        Class.forName("com.mysql.jdbc.Driver");
          Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/tnp","root","root");
          Statement smt=con.createStatement();  
          String query=" Select sname,fname,mname,gender,dob,emailid,mobileno,address,branch,college,semester,tenpass,tenper,twelvepass,twelveper,onepass,oneper,twopass,twoper,threepas,threeper,fourpass,fourper,nation,lang,objective,aggregate from (applicant) where loginid='"+loginid+"';";
          
          java.sql.ResultSet rs=smt.executeQuery(query);
          while (rs.next())
          { String sname=rs.getString(1);
            String fname=rs.getString(2);
           String mname=rs.getString(3);
            String gender=rs.getString(4);
            String dob=rs.getString(5);
            String email=rs.getString(6);
           String mobile1=rs.getString(7);
            String address=rs.getString(8);
           String branch=rs.getString(9);
           String college=rs.getString(10);
           String semester1=rs.getString(11);
           String tenpass1=rs.getString(12);
           String tenper1=rs.getString(13);
           String twelvepass1=rs.getString(14);
           String twelveper1=rs.getString(15);
           String onepass1=rs.getString(16);
           String oneper1=rs.getString(17);
           String twopass1=rs.getString(18);
           String twoper1=rs.getString(19);
           String threepass1=rs.getString(20);
           String threeper1=rs.getString(21);
           String fourpass1=rs.getString(22);
           String fourper1=rs.getString(23);
            String nationality =rs.getString(24);
          String language=rs.getString(25);
           String objective=rs.getString(26);
           String aggregate=rs.getString(27);
          Thirdb1.setText(sname);
          Fourthb1.setText(fname);
          fifthb1.setText(mname);
          jTextField1.setText(gender);
          Seventb1.setText(dob);
          Eightb1.setText(email);
          Nineb1.setText(mobile1);
          Tenb1.setText(address);
          Elevenb1.setText(branch);
          Twelveb1.setText(college);
          Thirteenb1.setText(semester1);
          Fourteend1.setText(tenpass1);
          Fourteenb1.setText(tenper1);
          Fifteend1.setText(twelvepass1);
          Fifteenb1.setText(twelveper1);
          Sixteenb1.setText(onepass1);
          Sixteend1.setText(oneper1);
          Seventeend1.setText(twopass1);
          Seventeenb1.setText(twoper1);
          Eighteend2.setText(threepass1);
          Eighteenb2.setText(threeper1);
          Nineteend2.setText(fourpass1);
          Nineteenb2.setText(fourper1);
          Twentyb2.setText(nationality);
          Twentyoneb3.setText(language);
          Twentytwob3.setText(objective);
          jTextField2.setText(aggregate);
          
                  
          }
      smt.close();
      rs.close();
      con.close();
      }
      catch(Exception e)
      { JOptionPane.showMessageDialog(null,"Error in Connection");
          System.out.println(e);
      }            
        
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void Thirdb2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Thirdb2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Thirdb2ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(viewcv.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(viewcv.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(viewcv.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(viewcv.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new viewcv().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Eighta1;
    private javax.swing.JTextField Eightb1;
    private javax.swing.JLabel Eighteena2;
    private javax.swing.JTextField Eighteenb2;
    private javax.swing.JLabel Eighteenc2;
    private javax.swing.JTextField Eighteend2;
    private javax.swing.JLabel Elevena1;
    private javax.swing.JTextField Elevenb1;
    private javax.swing.JLabel Fifteena1;
    private javax.swing.JTextField Fifteenb1;
    private javax.swing.JLabel Fifteenc1;
    private javax.swing.JTextField Fifteend1;
    private javax.swing.JLabel Fourteena1;
    private javax.swing.JTextField Fourteenb1;
    private javax.swing.JLabel Fourteenc1;
    private javax.swing.JTextField Fourteend1;
    private javax.swing.JLabel Fourtha1;
    private javax.swing.JTextField Fourthb1;
    private javax.swing.JLabel Ninea1;
    private javax.swing.JTextField Nineb1;
    private javax.swing.JLabel Nineteena2;
    private javax.swing.JTextField Nineteenb2;
    private javax.swing.JLabel Nineteenc2;
    private javax.swing.JTextField Nineteend2;
    private javax.swing.JPanel Secentha1;
    private javax.swing.JTextField Seventb1;
    private javax.swing.JLabel Seventeena1;
    private javax.swing.JTextField Seventeenb1;
    private javax.swing.JLabel Seventeenc1;
    private javax.swing.JTextField Seventeend1;
    private javax.swing.JLabel Seventha1;
    private javax.swing.JLabel Sixteena1;
    private javax.swing.JTextField Sixteenb1;
    private javax.swing.JLabel Sixteenc1;
    private javax.swing.JTextField Sixteend1;
    private javax.swing.JLabel Sixtha1;
    private javax.swing.JLabel Sixtha2;
    private javax.swing.JLabel Tena1;
    private javax.swing.JTextArea Tenb1;
    private javax.swing.JLabel Thirda1;
    private javax.swing.JLabel Thirda2;
    private javax.swing.JTextField Thirdb1;
    private javax.swing.JTextField Thirdb2;
    private javax.swing.JLabel Thirteena1;
    private javax.swing.JTextField Thirteenb1;
    private javax.swing.JLabel Twelvea1;
    private javax.swing.JTextField Twelveb1;
    private javax.swing.JLabel Twentya2;
    private javax.swing.JTextField Twentyb2;
    private javax.swing.JLabel Twentyonea3;
    private javax.swing.JTextField Twentyoneb3;
    private javax.swing.JLabel Twentytwoa3;
    private javax.swing.JTextArea Twentytwob3;
    private javax.swing.JLabel fiftha1;
    private javax.swing.JTextField fifthb1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JLabel second1;
    // End of variables declaration//GEN-END:variables
}
