/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tnp;

/**
 *
 * @author Tanya
 */
public class CV extends javax.swing.JFrame {

    /**
     * Creates new form CV
     */
    public CV() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        Secentha = new javax.swing.JPanel();
        first = new javax.swing.JLabel();
        second = new javax.swing.JLabel();
        Thirda = new javax.swing.JLabel();
        Thirdb = new javax.swing.JTextField();
        Fourtha = new javax.swing.JLabel();
        Fourthb = new javax.swing.JTextField();
        fiftha = new javax.swing.JLabel();
        fifthb = new javax.swing.JTextField();
        Sixtha = new javax.swing.JLabel();
        Sixthb = new javax.swing.JRadioButton();
        Sixthc = new javax.swing.JRadioButton();
        Seventha = new javax.swing.JLabel();
        Seventb = new javax.swing.JTextField();
        Eighta = new javax.swing.JLabel();
        Eightb = new javax.swing.JTextField();
        Ninea = new javax.swing.JLabel();
        Nineb = new javax.swing.JTextField();
        Tena = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tenb = new javax.swing.JTextArea();
        Elevena = new javax.swing.JLabel();
        Elevenb = new javax.swing.JTextField();
        Twelvea = new javax.swing.JLabel();
        Twelveb = new javax.swing.JTextField();
        Thirteena = new javax.swing.JLabel();
        Thirteenb = new javax.swing.JTextField();
        Fourteena = new javax.swing.JLabel();
        Fourteenb = new javax.swing.JTextField();
        Fifteena = new javax.swing.JLabel();
        Fifteenb = new javax.swing.JTextField();
        Fourteend = new javax.swing.JTextField();
        Fourteenc = new javax.swing.JLabel();
        Fifteenc = new javax.swing.JLabel();
        Fifteend = new javax.swing.JTextField();
        Sixteena = new javax.swing.JLabel();
        Sixteenb = new javax.swing.JTextField();
        Sixteenc = new javax.swing.JLabel();
        Sixteend = new javax.swing.JTextField();
        Seventeena = new javax.swing.JLabel();
        Seventeenc = new javax.swing.JLabel();
        Seventeenb = new javax.swing.JTextField();
        Seventeend = new javax.swing.JTextField();
        Eighteena = new javax.swing.JLabel();
        Eighteenb = new javax.swing.JTextField();
        Eighteenc = new javax.swing.JLabel();
        Nineteend = new javax.swing.JTextField();
        Nineteena = new javax.swing.JLabel();
        Nineteenb = new javax.swing.JTextField();
        Nineteenc = new javax.swing.JLabel();
        Eighteend = new javax.swing.JTextField();
        Twentya = new javax.swing.JLabel();
        Twentyb = new javax.swing.JTextField();
        Twentyonea = new javax.swing.JLabel();
        Twentyoneb = new javax.swing.JTextField();
        Twentytwoa = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Twentytwob = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        Twentythree = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        first.setText("   Get In Touch");

        second.setText("Please fill up the details (These details will be used as CV)");

        Thirda.setText(" Student's Name");

        Thirdb.setText(" ");
        Thirdb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ThirdbActionPerformed(evt);
            }
        });

        Fourtha.setText(" Father's Name");

        Fourthb.setText(" ");

        fiftha.setText(" Mother's Name");

        fifthb.setText(" ");

        Sixtha.setText(" Gender");

        Sixthb.setText("Female");
        Sixthb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SixthbActionPerformed(evt);
            }
        });

        Sixthc.setText("Male");
        Sixthc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SixthcActionPerformed(evt);
            }
        });

        Seventha.setText(" DOB");

        Seventb.setText("dd/mm/yyyy");
        Seventb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SeventbActionPerformed(evt);
            }
        });

        Eighta.setText(" E-mail ID");

        Eightb.setText("  ");

        Ninea.setText(" Mobile Number");

        Nineb.setText(" ");
        Nineb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NinebActionPerformed(evt);
            }
        });

        Tena.setText(" Address");

        Tenb.setColumns(20);
        Tenb.setRows(5);
        jScrollPane1.setViewportView(Tenb);

        Elevena.setText("  Branch");

        Elevenb.setText(" ");

        Twelvea.setText(" College");

        Twelveb.setText(" ");

        Thirteena.setText(" Semester");

        Thirteenb.setText(" ");

        Fourteena.setText(" 10th ( %)");

        Fourteenb.setText(" ");

        Fifteena.setText(" 12th(%)");

        Fifteenb.setText("  ");

        Fourteend.setText(" ");

        Fourteenc.setText(" Passing Year");

        Fifteenc.setText(" Passing Year");

        Fifteend.setText("      ");

        Sixteena.setText(" 1st Year(%)");

        Sixteenb.setText(" ");

        Sixteenc.setText(" Passing Year");

        Sixteend.setText("    ");

        Seventeena.setText(" 2nd Year(%)");

        Seventeenc.setText(" Passing Year");

        Seventeenb.setText(" ");

        Seventeend.setText("                ");

        javax.swing.GroupLayout SecenthaLayout = new javax.swing.GroupLayout(Secentha);
        Secentha.setLayout(SecenthaLayout);
        SecenthaLayout.setHorizontalGroup(
            SecenthaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SecenthaLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(SecenthaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SecenthaLayout.createSequentialGroup()
                        .addGroup(SecenthaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(Fifteena, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Fourteena, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)
                            .addComponent(Thirteena, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Twelvea, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(SecenthaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(SecenthaLayout.createSequentialGroup()
                                .addGroup(SecenthaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Twelveb)
                                    .addComponent(Thirteenb, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE))
                                .addGap(18, 18, 18))
                            .addGroup(SecenthaLayout.createSequentialGroup()
                                .addGroup(SecenthaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(Fifteenb, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
                                    .addComponent(Fourteenb, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Sixteenb)
                                    .addComponent(Seventeenb))
                                .addGap(30, 30, 30)
                                .addGroup(SecenthaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Fourteenc, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Fifteenc, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Sixteenc, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Seventeenc, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(10, 10, 10)))
                        .addGroup(SecenthaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Fifteend)
                            .addComponent(Fourteend))
                        .addGap(118, 118, 118))
                    .addGroup(SecenthaLayout.createSequentialGroup()
                        .addGroup(SecenthaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(SecenthaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(SecenthaLayout.createSequentialGroup()
                                    .addComponent(Elevena, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(Elevenb, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, SecenthaLayout.createSequentialGroup()
                                    .addGroup(SecenthaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(Seventha, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(Tena, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(Ninea)
                                        .addComponent(Eighta, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(18, 18, 18)
                                    .addGroup(SecenthaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(Seventb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(Eightb, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(Nineb, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(SecenthaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(Sixthc, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(SecenthaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, SecenthaLayout.createSequentialGroup()
                                        .addComponent(fiftha, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(fifthb))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, SecenthaLayout.createSequentialGroup()
                                        .addComponent(Fourtha, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(Fourthb))
                                    .addGroup(SecenthaLayout.createSequentialGroup()
                                        .addComponent(Thirda, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(Thirdb, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, SecenthaLayout.createSequentialGroup()
                                        .addComponent(Sixtha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Sixthb, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(SecenthaLayout.createSequentialGroup()
                                .addGroup(SecenthaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(Seventeena, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Sixteena, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(220, 220, 220)
                                .addGroup(SecenthaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Seventeend, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Sixteend, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(SecenthaLayout.createSequentialGroup()
                                .addGap(94, 94, 94)
                                .addComponent(second, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 86, Short.MAX_VALUE))))
            .addGroup(SecenthaLayout.createSequentialGroup()
                .addGap(187, 187, 187)
                .addComponent(first, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        SecenthaLayout.setVerticalGroup(
            SecenthaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SecenthaLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(first)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(second)
                .addGroup(SecenthaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SecenthaLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(SecenthaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Thirda, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Thirdb))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(SecenthaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Fourtha)
                            .addComponent(Fourthb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(SecenthaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fiftha)
                            .addComponent(fifthb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(SecenthaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Sixtha)
                            .addComponent(Sixthb))
                        .addGap(5, 5, 5)
                        .addComponent(Sixthc)
                        .addGap(18, 18, 18)
                        .addGroup(SecenthaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Seventha, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Seventb, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(SecenthaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Eighta)
                            .addComponent(Eightb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(SecenthaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Ninea, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Nineb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(SecenthaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Tena)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(13, 13, 13)
                        .addGroup(SecenthaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Elevena)
                            .addComponent(Elevenb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(SecenthaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Twelvea)
                            .addComponent(Twelveb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Thirteena))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SecenthaLayout.createSequentialGroup()
                        .addGap(380, 380, 380)
                        .addComponent(Thirteenb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(SecenthaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Fourteena)
                    .addGroup(SecenthaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Fourteenb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Fourteend, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Fourteenc)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(SecenthaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Fifteend, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(SecenthaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Fifteena)
                        .addComponent(Fifteenb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Fifteenc)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(SecenthaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Sixteena)
                    .addComponent(Sixteenb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Sixteenc)
                    .addComponent(Sixteend, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(SecenthaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Seventeena)
                    .addComponent(Seventeenc)
                    .addComponent(Seventeenb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Seventeend, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        Eighteena.setText("3rd Year(%)");

        Eighteenb.setText(" ");
        Eighteenb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EighteenbActionPerformed(evt);
            }
        });

        Eighteenc.setText(" Passing Year");

        Nineteend.setText(" ");
        Nineteend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NineteendActionPerformed(evt);
            }
        });

        Nineteena.setText("4th Year(%)");

        Nineteenb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NineteenbActionPerformed(evt);
            }
        });

        Nineteenc.setText(" Passing Year");

        Eighteend.setText("                ");
        Eighteend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EighteendActionPerformed(evt);
            }
        });

        Twentya.setText("Nationality");

        Twentyb.setText(" ");

        Twentyonea.setText("Languages");

        Twentyoneb.setText(" ");
        Twentyoneb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TwentyonebActionPerformed(evt);
            }
        });

        Twentytwoa.setText("Objective");

        Twentytwob.setColumns(20);
        Twentytwob.setRows(5);
        jScrollPane2.setViewportView(Twentytwob);

        jButton1.setText("Submit");

        Twentythree.setText("Click here to attach file");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Secentha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Twentytwoa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Twentyonea, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Twentya, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Eighteena, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Nineteena, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Eighteenb)
                                    .addComponent(Nineteenb, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE))
                                .addGap(36, 36, 36)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Eighteenc, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Nineteenc, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(35, 35, 35)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Eighteend, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Nineteend, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(Twentyoneb, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                                    .addComponent(Twentyb, javax.swing.GroupLayout.Alignment.LEADING)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(Twentythree, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(176, 176, 176)
                        .addComponent(jButton1)))
                .addContainerGap(119, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(Secentha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Eighteena, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Eighteenb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Eighteenc)
                    .addComponent(Eighteend, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Nineteena)
                    .addComponent(Nineteenb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Nineteenc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Nineteend, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Twentya)
                    .addComponent(Twentyb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Twentyonea)
                    .addComponent(Twentyoneb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Twentytwoa)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addComponent(Twentythree)
                .addGap(30, 30, 30)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NinebActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NinebActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NinebActionPerformed

    private void SeventbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SeventbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SeventbActionPerformed

    private void SixthcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SixthcActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SixthcActionPerformed

    private void SixthbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SixthbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SixthbActionPerformed

    private void ThirdbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ThirdbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ThirdbActionPerformed

    private void NineteenbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NineteenbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NineteenbActionPerformed

    private void EighteenbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EighteenbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EighteenbActionPerformed

    private void NineteendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NineteendActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NineteendActionPerformed

    private void EighteendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EighteendActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EighteendActionPerformed

    private void TwentyonebActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TwentyonebActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TwentyonebActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CV().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Eighta;
    private javax.swing.JTextField Eightb;
    private javax.swing.JLabel Eighteena;
    private javax.swing.JTextField Eighteenb;
    private javax.swing.JLabel Eighteenc;
    private javax.swing.JTextField Eighteend;
    private javax.swing.JLabel Elevena;
    private javax.swing.JTextField Elevenb;
    private javax.swing.JLabel Fifteena;
    private javax.swing.JTextField Fifteenb;
    private javax.swing.JLabel Fifteenc;
    private javax.swing.JTextField Fifteend;
    private javax.swing.JLabel Fourteena;
    private javax.swing.JTextField Fourteenb;
    private javax.swing.JLabel Fourteenc;
    private javax.swing.JTextField Fourteend;
    private javax.swing.JLabel Fourtha;
    private javax.swing.JTextField Fourthb;
    private javax.swing.JLabel Ninea;
    private javax.swing.JTextField Nineb;
    private javax.swing.JLabel Nineteena;
    private javax.swing.JTextField Nineteenb;
    private javax.swing.JLabel Nineteenc;
    private javax.swing.JTextField Nineteend;
    private javax.swing.JPanel Secentha;
    private javax.swing.JTextField Seventb;
    private javax.swing.JLabel Seventeena;
    private javax.swing.JTextField Seventeenb;
    private javax.swing.JLabel Seventeenc;
    private javax.swing.JTextField Seventeend;
    private javax.swing.JLabel Seventha;
    private javax.swing.JLabel Sixteena;
    private javax.swing.JTextField Sixteenb;
    private javax.swing.JLabel Sixteenc;
    private javax.swing.JTextField Sixteend;
    private javax.swing.JLabel Sixtha;
    private javax.swing.JRadioButton Sixthb;
    private javax.swing.JRadioButton Sixthc;
    private javax.swing.JLabel Tena;
    private javax.swing.JTextArea Tenb;
    private javax.swing.JLabel Thirda;
    private javax.swing.JTextField Thirdb;
    private javax.swing.JLabel Thirteena;
    private javax.swing.JTextField Thirteenb;
    private javax.swing.JLabel Twelvea;
    private javax.swing.JTextField Twelveb;
    private javax.swing.JLabel Twentya;
    private javax.swing.JTextField Twentyb;
    private javax.swing.JLabel Twentyonea;
    private javax.swing.JTextField Twentyoneb;
    private javax.swing.JButton Twentythree;
    private javax.swing.JLabel Twentytwoa;
    private javax.swing.JTextArea Twentytwob;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel fiftha;
    private javax.swing.JTextField fifthb;
    private javax.swing.JLabel first;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel second;
    // End of variables declaration//GEN-END:variables
}
